version: '3'
services:
    mysql:
        build:
            context: .
            dockerfile: sql/Dockerfile
        container_name: "mysql"
        environment:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: go_database
          MYSQL_USER: go_user
          MYSQL_PASSWORD: go_password
          TZ: Asia/Tokyo
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
    mainapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "main"
        depends_on: 
            - mysql
        volumes:
            - ./public:/public
        ports:
            - 443:443
            - 80:80
volumes:
    mysql_data:
    